### ISSUE TITLE
H徽商期货 交易服务器登录失败,CTP:不合法的登录

### ISSUE THREAD

**Issue by 4ever911** [shinnytech/tqsdk-python#100]
我的CTP是二席， 用https://shinnytech.github.io/shinny-futures-web 指定CTP 2席可以登陆成功，用文华指定二席也能成功登陆。

新版本代码可以在 TqAccount创建时指定 broker 和front_url， 我打电话给期货公司，他们不提供地址给我，说软件需要穿透监管，我看了shinny-futures-web 代码，里面也没有服务器的地址列表， 不过demo可以登陆。

麻烦能不能告诉我H徽商期货 CTP 2席的broker id 和 front url？

**Comment by 4ever911** [comment]
刚才看了下，新版本代码可以在 TqAccount创建时指定 broker 和front_url， 我打电话给期货公司，他们不提供地址给我，说软件需要穿透监管，我看了shinny-futures-web 代码，里面也没有服务器的地址列表， demo可以登陆。

麻烦能不能告诉我H徽商期货 CTP 2席的broker id 和 front url？

**Comment by 4ever911** [comment]
![Screenshot from 2019-07-24 23-07-20](https://user-images.githubusercontent.com/20335767/61841690-28a36580-aec8-11e9-9c91-371e84cedf04.png)

**Comment by xujx02** [comment]
请问最后怎么解决的？api = TqApi(TqAccount("H徽商期货", account, password))  这样可以吗？我马上要在徽商期货开户，需要让期货公司开通CTP1 还是 CTP2 ？
