### ISSUE TITLE
tqsdk.tools.downloader 数据下载工具 官方示范代码无效

### ISSUE THREAD

**Issue by archerhu77** [shinnytech/tqsdk-python#104]
https://doc.shinnytech.com/pysdk/latest/reference/tqsdk.tools.download.html
当中有几个问题：
1.案例缺少 from datetime import date
2.案例执行成功，但是没有数据存入csv，以下代码依照官方案例做了少量修改，但是拿不到数据：

from datetime import date
from contextlib import closing
from tqsdk import TqApi, TqSim
from tqsdk.tools import DataDownloader

api = TqApi(TqSim())
download_tasks = {}
download_tasks["SR_daily"] = DataDownloader(api, symbol_list=["CZCE.SR909", "CZCE.SR910", "CZCE.SR911"], dur_sec=24 * 60 * 60,
                    start_dt=date(2019, 7, 31), end_dt=date(2018, 8, 1), csv_file_name="kline.csv")

with closing(api):
    while not all([v.is_finished() for v in download_tasks.values()]):
        api.wait_update()
        print("progress: ", {k: ("%.2f%%" % v.get_progress()) for k, v in download_tasks.items()})

结果生成的csv无内容：
ls -l
总用量 8
-rw-r--r-- 1 root root   0 8月   1 10:14 kline.csv

测试基于tqsdk 0.9.8

**Comment by nealchenzhang** [comment]
end_dt在start_dt之前。。

**Comment by archerhu77** [comment]
明白，是我的低级错误，但是例子上少了from datetime import date的引用

谢谢!
