### ISSUE TITLE
tqsdk接口get_quote拿到的持仓量数据和博易、文华的持仓量差异很大

### ISSUE THREAD

**Issue by archerhu77** [shinnytech/tqsdk-python#106]
api.get_quote('DCE.eg1909')['open_interest']
跟文华、博易的持仓量数据差异非常大，几乎有两倍，是不是接口数据有问题？

测试基于tqsdk 0.9.8
![0FD55ECB6E47EBE79347D9A39CC01EFF](https://user-images.githubusercontent.com/26179312/62388792-d251b900-b590-11e9-8565-0099c4671817.png)

**Comment by we4t** [comment]
图中查询的两个持仓不是同一个合约代码： 
右上角命令行中查询的是eg1909，是甘醇1909 ；右下红色方框中的持仓量为鸡蛋1909，其合约代码为jd1909。

**Comment by archerhu77** [comment]
后来经过群友提示发现了这个低级错误，不好意思
