### ISSUE TITLE
模拟运行时委托单状态一直显示'alive'

### ISSUE THREAD

**Issue by xujx02** [shinnytech/tqsdk-python#107]
连接到天勤终端模拟账户运行时，委托单在终端中已成交，但是tqsdk中order.status一直显示alive. 

#!/usr/bin/env python
#  -*- coding: utf-8 -*-

from tqsdk import TqApi
api = TqApi(天勤终端模拟账号)
symbol="DCE.m1909"
q=api.get_quote(symbol)
order = api.insert_order(symbol=symbol, direction="BUY", offset="OPEN",\
                                     limit_price=None,volume=1)
while True:
    api.wait_update()
    print(order.status)

**Comment by we4t** [comment]
bug：
teqsdk对接天勤时，下单成功后天勤终端显示“全部成交”, 但此时天勤未将更新数据包转发给tqsdk,
