### ISSUE TITLE
何时能支持查日结单?

### ISSUE THREAD

**Issue by archerhu77** [shinnytech/tqsdk-python#109]
CTP有的功能，可以查到历史成交和出入金

**Comment by we4t** [comment]
增加查结算单的这个需求我们先记下来了

**Comment by archerhu77** [comment]
> 增加查结算单的这个需求我们先记下来了

过了两个版本都还没列上to-do，计划哪个版本才增加呢？

**Comment by shinny-tianqin** [comment]
因为结算单的格式并不便于代码处理, TqSdk 不准备专门提供结算单查询接口. 后期计划增加完整的历史报告查询接口, 以更利于程序使用的方式提供更详细的历史数据.
