### ISSUE TITLE
建议增加tqapi的构建方法，使得生成实例的时候可以指定timeout参数

### ISSUE THREAD

**Issue by archerhu77** [shinnytech/tqsdk-python#110]
建议增加tqapi的构建方法，使得生成实例的时候可以指定timeout参数，这样子针对不同的场景可以设置不同的timeout，而不是傻傻地等60秒，又或者改一个数值所有操作都要apply（毕竟有些查询是需要一定时间的）

**Comment by shinny-tianqin** [comment]
TqApi构建超时失败, 是因为合约服务/行情服务/交易服务中至少有一项超时无回应. 此时TqApi一定无法正常工作. 可否说明一下需要缩短超时等待时间有何作用?

**Comment by archerhu77** [comment]
有一些环境，可以确认网络很稳定，出问题一定是你提到的服务没有响应，这种情况下需要一个合理比较短的超时时间，把错误状态发送给管理员，以便手动跟进平仓或者止损，而不是傻傻地等60秒后才知道
