### ISSUE TITLE
t80示例策略提供的平仓方式无法平仓

### ISSUE THREAD

**Issue by aijy** [shinnytech/tqsdk-python#113]
使用t80示例策略的方法，下单可以成功，平仓是提示“要撤销的单不存在 ”，一直无法平仓。请查看下这种将目标品种仓位变为0的方式平仓是不是内部实现有问题。

**Comment by we4t** [comment]
0.9.15版本tqsdk：测试t80 暂时未触发此提示“要撤销的单不存在 ”，无法平仓问题也未重现，待后期检查

**Comment by aijy** [comment]
新版本已经没有这个问题了
