### ISSUE TITLE
ta指标在天勤中画图的示例程序说明加强

### ISSUE THREAD

**Issue by we4t** [shinnytech/tqsdk-python#116]

**Comment by kingdjf** [comment]
一直没画出图来，原例程t90可以正确执行，但看不到draw_text输出

**Comment by kingdjf** [comment]
OK 搞定了，close吧

**Comment by we4t** [comment]
“技术指标绘图示例” 在天勤官网的教程中：https://www.shinnytech.com/blog/%e6%8a%80%e6%9c%af%e6%8c%87%e6%a0%87%e7%bb%98%e5%9b%be%e4%bd%bf%e7%94%a8%e7%a4%ba%e4%be%8b/
