### ISSUE TITLE
程序化交易订单有异常显示

### ISSUE THREAD

**Issue by aijy** [shinnytech/tqsdk-python#117]
![image](https://user-images.githubusercontent.com/31498816/63258680-29ed6580-c2af-11e9-85fb-7349a64dda40.png)
策略运行过程中出现订单异常，不知道异常原因。

**Comment by aijy** [comment]
如图片中au1909订单所示

**Comment by shinny-tianqin** [comment]
请问是哪个期货公司的账号? 方便写下账号么?

**Comment by aijy** [comment]
快期模拟 9016126628
