### ISSUE TITLE
[BUG?]在0.9.17的Position对象找不到pos_long和pos_short

### ISSUE THREAD

**Issue by archerhu77** [shinnytech/tqsdk-python#133]
文档写着：
volume_long = None
期货公司查询的多头手数 (不推荐, 推荐使用pos_long)

但是从0.9.17 tqsdk收到的Postion对象内容，完全找不到pos_long和pos_short，难道是漏了？

这是收到的实际数据：
<tqsdk.objs.Position object at 0x7fd54e8278d0>, D({'exchange_id': 'SHFE', 'instrument_id': 'ag1912', 'pos_long_his': 40, 'pos_long_today': 10, 'pos_short_his': 0, 'pos_short_today': 0, 'volume_long_today': 10, 'volume_long_his': 40, 'volume_long': 50, 'volume_long_frozen_today': 0, 'volume_long_frozen_his': 0, 'volume_long_frozen': 0, 'volume_short_today': 0, 'volume_short_his': 0, 'volume_short': 0, 'volume_short_frozen_today': 0, 'volume_short_frozen_his': 0, 'volume_short_frozen': 0, 'open_price_long': 4249.8, 'open_price_short': 0.0, 'open_cost_long': 3187350.0, 'open_cost_short': 0.0, 'position_price_long': 4569.8, 'position_price_short': 0.0, 'position_cost_long': 3427350.0, 'position_cost_short': 0.0, 'float_profit_long': 237150.0, 'float_profit_short': 0.0, 'float_profit': 237150.0, 'position_profit_long': -2850.0, 'position_profit_short': 0.0, 'position_profit': -2850.0, 'margin_long': 274380.0, 'margin_short': 0.0, 'margin': 274380.0, 'user_id': '135763', 'volume_long_yd': 50, 'volume_short_yd': 0, 'last_price': 4566.0})

**Comment by we4t** [comment]
这两个字段是有的，https://github.com/shinnytech/tqsdk-python/blob/master/tqsdk/objs.py#L288，
因为是计算出来的，然后用@property装饰器变成属性，不在Position的__dict__的items序列里。所以直接输出position就看不到这两个属性，但它是和其他属性一样可以正常调用使用

**Comment by archerhu77** [comment]
这里觉得文档是一个误导，这两个值等于是函数返回结果，而不是直接返回的值的内容，但是文字的表达上却用了同样的方式，很容易误导啊

**Comment by archerhu77** [comment]
而且我觉得，原本有volume_long和volume_short，新版本不建议使用却没有直接对应可以使用的值，这样设计不太合理吧？原本的程序全部都不能只是改一下值而平滑过度了

**Comment by we4t** [comment]
pos_xxx 和 volume_xxx的区别：
在定义上：pos_xxx是根据交易所的计算规则计算的手数，volume_xxx是根据ctp的计算规则计算的手数；
在现在实际使用中：实盘是直接把从ctp获取到的volume_xxx显示出来（没有再经过其他的计算修改）;pos_xxx是只要有成交之后服务器就立即修改的。

pos_long_xxx存在的原因：每次成交后服务器会去ctp查询持仓信息，在发送查询指令和收到返回的数据之间有时间延迟，此时如果用户去查询持仓信息，就会不准确（因为新数据还未收到），因此现在推荐使用pos_xxx（它是服务器在收到成交信息后就立即根据成交手数计算的，因此更新很及时）。

volume_xxx暂时存在，但不建议使用，尚未确定之后会不会去掉这个字段。(volume_long和volume_short对应使用的值就是pos_long和pos_short，数值是一样的，只是pos_xxx更新会更快）

**Comment by archerhu77** [comment]
好的，那我想想如何改吧，谢谢
