### ISSUE TITLE
直连服务器后使用downloader内存泄露

### ISSUE THREAD

**Issue by yangguang760** [shinnytech/tqsdk-python#135]
原来先启天勤终端，再用sdk连终端ws端口使用downloader下载数据时正常。
升级sdk版本并改为直连服务器后，可正常下载数据，但内存占用一直上升，直至无内存可用然后被系统kill。
推测是python的ws存在内存泄露。

**Comment by yangguang760** [comment]
更新，每次使用downloader后，close api，再新初始化api给下一个downloader用，可以绕过内存泄露问题。

**Comment by we4t** [comment]
0.9.18版已修复此bug ，相关commits : cdf1373cfc47b8d5268cdbdaa2a5d9a11299a06d , 8e25a17e4856d4e2fb16352141f89cb32685730e
