### ISSUE TITLE
tafunc请提供barslast，valuewhen两个函数。

### ISSUE THREAD

**Issue by pqctp** [shinnytech/tqsdk-python#136]

**Comment by we4t** [comment]
请问这两个函数是做什么用的？

**Comment by pqctp** [comment]
VALUEWHEN(COND,X) 当COND条件成立时，取X的当前值。如COND条件不成立，则取上一次COND条件成立时X的值。

注：
X可以是数值也可以是条件。

例1
VALUEWHEN(HIGH>REF(HHV(HIGH,5),1),HIGH);表示当前最高价大于前五个周期最高价的最大值时返回当前最高价
例2：
VALUEWHEN(DATE<>REF(DATE,1),O);表示取当天第一根k线的开盘价（即当天开盘价）
例3：
VALUEWHEN(DATE<>REF(DATE,1),L>REF(H,1));//表示在当天第一根k线上判断当前最低价是否大于昨天最后一根K线的最高价。返回1，说明当天跳空高开。返回0，说明当天不满足跳空高开条件。

**Comment by pqctp** [comment]
BARSLAST(COND)：上一次条件COND成立到当前的周期数

注：
1、条件成立的当根k线上BARSLAST(COND)的返回值为0

例1：
BARSLAST(OPEN>CLOSE); //上一根阴线到现在的周期数。
例2：
N:=BARSLAST(DATE<>REF(DATE,1))+1;//分钟周期，当日k线数。
//由于条件成立的当根k线上BARSLAST(COND)的返回值为0，所以“+1”才是当日k线根数。

**Comment by shinny-mayanqiong** [comment]
fix by commit 65943a2
