### ISSUE TITLE
api.draw_line函数绘的图在天勤终端显示不正确？

### ISSUE THREAD

**Issue by xcgoo** [shinnytech/tqsdk-python#138]
在策略中想利用api.draw_line绘制信号线（线段），打印日志显示开、平点数据都是正确的，但是显示出来的结果都是水平直线，不知道是sdk的bug还是天勤终端的bug，貌似“SEG”、“RAY”均不起作用，都会绘制成直线。
绘图语句示例：
    if longamt < prelongamt:  #如果有平仓，则绘制信号线
        api.draw_line(klines, lox, loy, kid, kclose, line_type="SEG", color=0xFF0000FF)
        print(f"cover long: lox:{lox}, loy:{loy}, lcx:{kid}, lcy:{kclose}")
        lox = None  #开仓位置, long open x
        loy = None  #开仓位置, long open y

**Comment by we4t** [comment]
如果要画线段，x1、y1、x2、y2都应该有值，你的这几个参数是什么值呢？

**Comment by we4t** [comment]
请试用一下以下代码，看在天勤终端是否能画出线段？
from tqsdk import TqApi, TqSim

api = TqApi()
klines = api.get_kline_serial("SHFE.cu1912", 86400)
api.draw_line(klines, -4, klines.iloc[-4].close, -2, klines.iloc[-2].high, line_type="SEG", color=0xFF0000FF)

api.close()

**Comment by we4t** [comment]
api的画图示例已添加到demo目录下，如有需要请参考示例 t90 - t95
