### ISSUE TITLE
天勤终端人工交易时，套利指令无法平仓，只能开仓

### ISSUE THREAD

**Issue by xcgoo** [shinnytech/tqsdk-python#139]
在用天勤终端进行套利交易时，套利指令只能开仓，无法平仓，此外用TargetPosTask设置套利品种的目标持仓时，貌似也有问题。

**Comment by we4t** [comment]
天勤相关的问题请尽量转移到天勤官网论坛中提问。在天勤中手动下单，如果价格填写错误，或使用的为simnow账号，则无法下单，请问具体情况是怎么样的，有无报错提示？
” 用TargetPosTask设置套利品种的目标持仓有问题 “，请问报错信息是什么呢？
