### ISSUE TITLE
请问tqsdk内部通讯是直接调用CTP接口还是请求你们自己的接口？

### ISSUE THREAD

**Issue by maocis** [shinnytech/tqsdk-python#14]
请问tqsdk内部通讯是直接调用CTP接口还是请求你们自己的接口？

**Comment by maocis** [comment]
看到了，是调用的你们自己的封装接口，可以给出直接调用CTP版本的吗？
https://openmd.shinnytech.com/t/md/symbols/latest.json

**Comment by shinny-chengzhi** [comment]
是的，交易服务器是完全开源的。

**Comment by maocis** [comment]
太牛了，但是这样中转一次的话，岂不是增加了延时？

**Comment by shinny-chengzhi** [comment]
是的，但是中转本身的延迟通常远小于网络延迟，如果对延迟很敏感，也不会选 python 了

**Comment by maocis** [comment]
感谢解惑，行情可以自建网关吗?

**Comment by shinny-chengzhi** [comment]
行情由于牵扯到交易所授权和连接交易所的专线，因此不能自建

**Comment by basicsp** [comment]
行情最好不要自建，如果只是ticker还好，涉及到K线就非常麻烦了

**Comment by hardywu** [comment]
> tqsdk 交易功能是连接到 https://github.com/shinnytech/open-trade-gateway 之后再连接到 ctp
> 行情是连接到我们的行情服务器再连接到交易所，中间没有ctp

我们的延迟有1.4秒（系统时间- timestamp)。 这么高是正常延迟的吗？

**Comment by shinny-chengzhi** [comment]
本地时间不准的，找个不活跃的合约下个单，等到从行情上看到你的单子就可以算出来交易+行情的延迟了
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by hardywu** [comment]
ntp 同步后，延迟就小多了。
