### ISSUE TITLE
CTP account balance 没有更新

### ISSUE THREAD

**Issue by 4ever911** [shinnytech/tqsdk-python#140]
我在交易时段往账户里面转了一些钱，等了好久这个信息都没有更新到account数据里面，有做wait_update 操作。  同时我用文华登录看到CTP和普通登录都已经显示到账。

**Comment by we4t** [comment]
请问是否能重现呢？

**Comment by 4ever911** [comment]
可以的，刚才又发现，如果马上做一笔交易，这个balance就会马上更新， 如果不做交易，哪怕价格波动，这个balance也需要几分钟才能更新（文华在转账完成就更新了。）

**Comment by we4t** [comment]
我们这边不能重现，请私聊联系tqsdk交流群的管理员west，群号：619870862
