### ISSUE TITLE
平安期货实盘登录连接不上

### ISSUE THREAD

**Issue by loong-chen** [shinnytech/tqsdk-python#147]
提示  WARNING - 通知: 交易服务器登录失败,CTP:不合法的登录

**Comment by loong-chen** [comment]
账号和密码都没错

**Comment by we4t** [comment]
请问是主席还是次席呢？

**Comment by loong-chen** [comment]
> 请问是主席还是次席呢？

不是只需要提供，期货公司名称 ，账号，密码，3个参数么。我也不知道是主席还是次席。我是这么登录的  api = TqApi(TqAccount('P平安期货', 'xxxxx', 'xxxxx'))

**Comment by Qweringo** [comment]
> > 请问是主席还是次席呢？
> 
> 不是只需要提供，期货公司名称 ，账号，密码，3个参数么。我也不知道是主席还是次席。我是这么登录的 api = TqApi(TqAccount('P平安期货', 'xxxxx', 'xxxxx'))

平安期货主席是金仕达，tqsdk目前只支持ctp系统，如果你是平安期货，可以和客户经理联系把账户转移到ctp席位上，或者使用其他期货公司账号登录
