### ISSUE TITLE
回测时，quote总是从TqBacktest指定的start_dt前一天晚上收盘时刻开始

### ISSUE THREAD

**Issue by realoptimusprime** [shinnytech/tqsdk-python#15]
tqsdk 0.8.8; 天勤客户端0.9.4
订阅日线klines=api.get_kline_serial(symbol, 24 * 60 * 60)
获取quote=api.get_quote(symbol)
指定TqBacktest的start_dt为某个datetime,比如datetime(2018,9,4)
开始回测
api.wait_update()后等来的前两个quote是前一晚收盘时刻的两个tick的数据(rb对应2018-09-03 23:00:00)

**Comment by shinny-chengzhi** [comment]
回测相当于时间回退到 start_dt 时刻开始运行，因此当时看到的行情就是 start_dt 前的最后一笔行情

**Comment by realoptimusprime** [comment]
OK，那么回到这个问题https://github.com/shinnytech/tqsdk-python/issues/18
从回测开始当天的夜盘开始，为什么获得的quote不是21:00:00而是18:00:00
比如这里的日K变为2018-09-05 00:00:00时，获得quote是2018-09-04 18:00:00而不是2018-09-04 21:00:00

**Comment by shinny-chengzhi** [comment]
quote 的时间被标到 18:00:00 是因为 sdk 没有合约的交易时段信息，并不知道日线是到 15:00:00 还是 15:15:00 收盘，但是这个 18:00:00 quote 的价格应该和收盘的价格是一致的
