### ISSUE TITLE
回测结束之后,生成一个直接可在终端预览的文件

### ISSUE THREAD

**Issue by Lsgo** [shinnytech/tqsdk-python#152]
1.现在很多人在装vscode插件或者是终端时.运行回测都自动停止.然后对应的错误提示没有或者提示不明显找出了很多疑问
2.如果要进行多进程回测.且需要同时看到回测的结果.
以上两个痛点.我觉得可以直接在命令行运行回测

`
    from tqsdk import BacktestFinished

    acc = TqSim()

    try:
      api = TqApi(acc, backtest=TqBacktest(start_dt=date(2018, 5, 1), end_dt=date(2018, 10, 1)))
      #策略代码在这里
      #...

    except BacktestFinished as e:
      # 回测结束时会执行这里的代码
      print(acc.trade_log)
`

类似以上运行完回测之后.加一个方法.保存回测文件.就可以生成类似在终端回测完之后生成的文件.该文件可以直接被终端打开.看到相关的买卖点.
这样可以解决以上两个问题.谢谢

**Comment by we4t** [comment]
当前最新版更新的web_gui功能已经符合了需求，在命令行中运行策略，如果报错就能看到详细的错误信息，并且在回测时能打开gui查看回测情况，详细使用方法查看文档中web_gui部分
