### ISSUE TITLE
用户密码包含特殊符号运行会报错

### ISSUE THREAD

**Issue by ElizabethMa** [shinnytech/tqsdk-python#153]
![image](https://user-images.githubusercontent.com/11316244/66809507-12092980-ef60-11e9-8c28-a8f85bb962e6.png)

**Comment by shinny-chengzhi** [comment]
调用方应确保参数填写正确,例如  linux 下执行 echo $sdfsdfs 什么都不显示，需要修改命令为 echo '$sdfsdfs'

**Comment by shinny-chengzhi** [comment]
如果比较难escape 可以考虑使用如 base64编码
