### ISSUE TITLE
增加模拟时交易时间判断

### ISSUE THREAD

**Issue by shinny-limin** [shinnytech/tqsdk-python#155]
防止TqSim模拟账号在非交易时间下单

**Comment by we4t** [comment]
订阅两个合约时，a的tick，b的K线，在19：35时a的tick更新，下b合约的委托单，导致成交

**Comment by we4t** [comment]
TqSim在回测时根据回测模块下发的current_dt(当前行情时间）来判断是否可交易； 
在盘中时，检查如果没有current_dt字段，即表示在盘中，此时获取本地时间来判断是否此时可交易
