### ISSUE TITLE
回测时，k线起始时间点无效

### ISSUE THREAD

**Issue by realoptimusprime** [shinnytech/tqsdk-python#16]
tqsdk 0.8.8; 天勤客户端0.9.4
订阅日线klines=api.get_kline_serial(symbol, 24 * 60 * 60)
获取quote=api.get_quote(symbol)
指定TqBacktest的start_dt为某个datetime,比如datetime(2018,9,4,9,0,0)
开始回测
api.wait_update()后每次读出来的klines[-1]["datetime"]对应的时间点总是下一天的00:00:00,而不是09:00:00

**Comment by shinny-chengzhi** [comment]
日线及N日线周期的 datetime 字段是交易日，所以时间部分始终是 00:00:00

**Comment by realoptimusprime** [comment]
这个需要在文档里写清楚。根据文档只要传入类型datetime就是具体时间点，不论K线周期

https://doc.shinnytech.com/pysdk/latest/reference.html#tqsdk.backtest.TqBacktest
_start_dt (date/datetime): 回测起始时间, 如果类型为 date 则指的是交易日, 如果为 datetime 则指的是具体时间点_
