### ISSUE TITLE
天勤1.1.0版本中，K线图表功能消失了？

### ISSUE THREAD

**Issue by kingdjf** [shinnytech/tqsdk-python#168]
![image](https://user-images.githubusercontent.com/20849778/67577602-61770300-f773-11e9-8d45-b5ae3d80d8ca.png)
不能在K线中加入图表，不知道是BUG还是我没用明白

**Comment by kingdjf** [comment]
准确讲应该是添加指标的功能没有了，添加不了均线，MACD等指标

**Comment by Qweringo** [comment]
添加指标功能以及去除，因为天勤终端之前使用的是talib计算的，和tqsdk自带的tasdk.ta某些指标的默认参数或者计算方式有些许出入，造成误解，所以暂时下架功能，以后如果统一更新指标计算方式到tqsdk.ta后会同步更新

**Comment by kingdjf** [comment]
好的，希望天勤越来越完善。
