### ISSUE TITLE
下单后无法取到正确的成交价格,有无方法？

### ISSUE THREAD

**Issue by victorzsl** [shinnytech/tqsdk-python#169]
如下的方法，下单后无法取到正确的成交价格，
target_pos.set_target_volume(1)
api.wait_update()
while not api.is_changing(trade):
 空 api.wait_update()
 空 if True:   #判断条件xxx
 空 格   lot = position.pos
 空 格   if lot>0 :
 空 格        openPrice = position.open_price_long
 空 格   elif lot<0:
 空 格        openPrice = position.open_price_short
 空 格   else:
 空 格        openPrice = 0
 空 格   print("openPrice",openPrice)
成交价格是延时一些毫秒后给出的。
api.is_changing(trade)触发后,position.open_price_short和position.open_price_long却没有及时更新。所以取到的价格是错误的。

如何写判断条件xxx？
数据结构position,trade里都没有标志，是否已成交，且返回正确的成交价格。
希望能给出正确的案例。

**Comment by kingdjf** [comment]
用inert_order下单，别用调仓下单。

**Comment by victorzsl** [comment]
建议框架给出解决方案，而不是用户适应这种缺陷。

**Comment by victorzsl** [comment]
![position change at when](https://user-images.githubusercontent.com/18364962/69109451-c8f24b00-0ab2-11ea-952f-5ee87a94eb22.JPG)

问题如图所示

**Comment by we4t** [comment]
你的trade和position是如何获取的？是否都是同一个合约的两个字段信息？或者trade是获取了所有的成交信息？

**Comment by shinny-tianqin** [comment]
这个问题源于目前order与trade信息没有做事务化同步. 计划在服务器端修改, 实现order/trade的事务化, 确保每次推送成交信息时都同步推送相应的委托单状态
