### ISSUE TITLE
回测时，quote生成规则在文档中描述矛盾

### ISSUE THREAD

**Issue by realoptimusprime** [shinnytech/tqsdk-python#17]
tqsdk 0.8.8

对于不订阅tick，但是订阅了3分钟K线的场景下，
- 根据1, quote应该按照3分钟为周期生成并更新
- 根据2, quote应该按照1分钟为周期生成并更新

1. _如果没有订阅 tick, 但是订阅了 k线, 则对应合约的 quote 会使用 k线生成, 更新频率和 k线的周期一致， 如果订阅了某个合约的多个周期的 k线, 则任一个周期的 k线有更新时, quote 都会更新_
2. _如果即没有订阅 tick, 也没有订阅 k线或订阅的 k线周期大于分钟线, 则 TqBacktest 会自动订阅分钟线来生成 quote_

**上述1和2均来自最新在线文档https://doc.shinnytech.com/pysdk/latest/reference.html#tqsdk.backtest.TqBacktest**

**Comment by shinny-chengzhi** [comment]
这两句话并不矛盾，因为 1 中提到的  “订阅 k线” 即包含了你自己订阅的 k 线，也包含了 TqBacktest 自动订阅的 k 线

**Comment by realoptimusprime** [comment]
1中”没有订阅 tick, 但是订阅了 k线“是一个假设的前提，TqBacktest自动订阅K线这个行为显然不能成为这个前提的一部分，否则的话这个”但是订阅了 k线“就是多余的，应该直接去掉。

这里的问题还是文档写的不够清晰准确，引起用户的猜测和歧义，需要更新文档，明确的指出”TqBacktest 会怎样自动订阅k 线来生成quote“

**Comment by shinny-chengzhi** [comment]
如果你有更好的表述方式，欢迎发 PR
