### ISSUE TITLE
TqApi（）默认TqSim，在网络中断，重新恢复的时候 ，貌似TqSim账户不会重新工作

### ISSUE THREAD

**Issue by Qweringo** [shinnytech/tqsdk-python#170]
描述：TqApi（）默认TqSim，在网络中断，重新恢复的时候 ，貌似TqSim账户不会重新工作

**Comment by Qweringo** [comment]
api是继续工作的，因为用api创建的协程部分还是会重新工作，记录的数据源是网络爬虫。也就是说，可能是恢复网络连接后，TqSim账户不会重新登录，以TqSim订阅的数据也就不会传输过来

**Comment by we4t** [comment]
此案例发生在下载数据时，尚未验证。在盘中测试运行策略时未触发此问题。
