### ISSUE TITLE
默认打开日志选项

### ISSUE THREAD

**Issue by shinny-chengzhi** [shinnytech/tqsdk-python#179]
需要处理日志滚动及多进程同时写日志

**Comment by shinny-tianqin** [comment]
* 建立一个默认日志文件目录
* 每个进程都应该输出到一个单独的日志文件
* 进程退出时, 对此目录中的存量日志文件进行清理, 删除N天前的日志文件

**Comment by shinny-mayanqiong** [comment]
related #177
