### ISSUE TITLE
回测时，quote时间和k线时间不一致

### ISSUE THREAD

**Issue by realoptimusprime** [shinnytech/tqsdk-python#18]
tqsdk 0.8.8; 天勤客户端0.9.4

订阅日线klines=api.get_kline_serial(symbol, 24 * 60 * 60)
获取quote=api.get_quote(symbol)
指定TqBacktest的start_dt为某个datetime,比如datetime(2018,9,4)
开始回测
api.wait_update()，从第二次klines[-1]["datetime"]发生变更开始(新的一天)，对应的quote["datetime"]总是等于前一天的18:00:00
比如klines[-1]["datetime"] 变成 2018-09-05 00:00:00时，quote["datetime"]变成2018-09-04 18:00:00

**Comment by shinny-chengzhi** [comment]
日线的 datetime 是交易日，而 quote 的 datetime 是自然时间， 2018-09-05 这个交易日是从 2018-09-04 晚上开始的。

**Comment by realoptimusprime** [comment]
交易晚上开始没问题，为什么夜盘第一个quote的datetime是18:00:00? 提供21:00:00的quote有什么问题？
