### ISSUE TITLE
关于 tq 的 K 线问题

### ISSUE THREAD

**Issue by zshchou** [shinnytech/tqsdk-python#181]
最近用了一段时间 tq，也和周边其它产品对比过，发现 tq的 K 线有个问题：
跨区结束时间居然是在下一个时间段出现 ，例如11:30:00的结束 K 线是没有的，13:30:00才是11:30:00的结束线，同样，2:30和15:00的也是没有的，
例如30分钟线，TQ 的序列是这样的：
10:30:00
11:00:00
_13:30:00_
14:00:00
其它产品是这样的：
10:30:00
11:00:00
_11:30:00_
14:00:00

我在 TQ回测中，收到13:30:00的 K 线，回测时间也是13:30:00，下单时间却是11:29:59.9999，结果就导致用将来的趋势去过去下单，出现了错误的利润。

希望官方能告知解决办法！

**Comment by we4t** [comment]
K线上的datetime是K线的开始时间，K线刚生成的时候高开低收数据都是上一个K线的收盘价。
下单时间的通知和策略代码中的print这两个输出文件的顺序是不保证的，直接你代码里的print的内容是在stdout文件里，info通知那一句是在stderr里。但stdout中的内容和stderr中的内容内部都是按照顺序来输出的

**Comment by we4t** [comment]
另外，你可以阅读看一下我们的K线是如何生成的
https://www.shinnytech.com/blog/why-our-kline-different/

**Comment by zshchou** [comment]
感谢回复，官方的 K 线生成逻辑我以前看过，其实 K 线怎么生成，这个也可以另说，关键是不能用未来趋势去过去下单：

下面日志中，前面：2016-01-04 13:30:00为 klines.iloc[-].datetime，
api._account.current_datetime和api._backtest.current_dt均为下午13:30:00，也就是说，回测的时间已经到下午了，这个时侯 quote.datetime 是11:29:59.999999，

下午开盘，收到了13:30:00的 K 线，其实就是11点到11：30的30分钟 K 线，也就是其它产品11:30:00这条 K 线。，然后进行下单操作，相当于在下午开盘时去下了上午收盘时的单。

> [2016-01-04 13:30:00] ag1606 模拟交易下单 3d7f69f0f3db82a716e7b501d92c765e: 时间:2016-01-04 11:29:59.999999,合约:SHFE.ag1606,开平:CLOSETODAY,方向:BUY,手数:1,价格:3286.0
> 模拟交易委托单 3d7f69f0f3db82a716e7b501d92c765e: 全部成交

**Comment by zshchou** [comment]
运行官方的例子，大量的跨区间交易：
11:29:59.999999
2:29:59.999999
14:59:59.999999
11:14:59.999999
这是不合理的，其实看到的正收入都是虚的，

- 这些时间点的操作是下一时间段算出来的
- 这些时间点开平仓就算能开，实际成功率也低

**Comment by we4t** [comment]
模拟交易打出的成交时间是取的当时的行情时间，也就是quote的时间。而回测时quote是由K线的收盘价来合成的。当遇到跨交易时段，K线有跳空，这一情况会引起quote数据的差异。这个我们之后会优化，issue为：https://github.com/shinnytech/tqsdk-python/issues/195

**Comment by zfsamzfsam** [comment]
K线,应该包括<K线起点时间(time_open)>,也应该包括<结束时间(time_close)>,如果time_close不能由time_open计算出来的话!!!

**Comment by we4t** [comment]
我们的K线上的datetime是这个K线的起始时间，截止时间也可以当作是下一个K线的起始时间之前，也就是datetime + 周期，K线的周期肯定是有的
