### ISSUE TITLE
if api.is_changing(account, "avaliable"):判断不往下走

### ISSUE THREAD

**Issue by Qweringo** [shinnytech/tqsdk-python#182]
![BYVJ1A72Q@KOQ6$R)(MJF}5](https://user-images.githubusercontent.com/49545435/68265987-9abf4500-0088-11ea-87a2-c2b3a9d3b375.png)

`from tqsdk import TqApi ,TqAccount, TargetPosTask

SYMBOL = 'SHFE.rb2001'
api = TqApi(TqAccount("simnow","022633","123456"))
quote = api.get_quote(SYMBOL) #获取行情数据
klines = api.get_kline_serial(SYMBOL, 24*60*60) #获取日线
account = api.get_account() #用户账户资金信息
positions=api.get_position(SYMBOL) #用户持仓信息

保证金1=0

def deposite():
    '''
    保证金比例
    '''
    跌停价=quote.lower_limit
    涨停价=quote.upper_limit
    原可用资金=account.available
    合约乘数=quote.volume_multiple
    保证金=0
    if 涨停价-quote.last_price>quote.last_price-跌停价:
        print('多 原可用资金=%.2f'%(account.available))
        order = api.insert_order(symbol=SYMBOL, direction="BUY", offset="OPEN",volume=1, limit_price=跌停价) #多
        while 1:
            api.wait_update()
            if api.is_changing(account, "avaliable"): #可用资金有变化
                print('当前可用资金=',account.available)
                占用保证金=原可用资金-account.available
                api.cancel_order(order) #撤未成交的委托单
                保证金=round(占用保证金/合约乘数/quote.bid_price1,2)*100
                print('占用保证金=%.2f，保证金=%.2f'%(占用保证金,保证金))
                break
    else:
        print('空 原可用资金=%.2f'%(account.available))
        order = api.insert_order(symbol=SYMBOL, direction="SELL", offset="OPEN",volume=1, limit_price=涨停价)
        print(order)
        n=0
        while 1:
            api.wait_update()
            n+=1
            print('n=',n,' account.available=',account.available)
            print('n=',n,order)
            if api.is_changing(account, "avaliable"): #可用资金有变化
                print('当前可用资金=',account.available)
                占用保证金=原可用资金-account.available
                api.cancel_order(order) #撤未成交的委托单
                保证金=round(占用保证金/合约乘数/quote.ask_price1,2)*100
                print('占用保证金=%.2f，保证金=%.2f'%(占用保证金,保证金))
                break
    return 保证金

while True:
    api.wait_update()
    if 保证金1==0:
        保证金1=deposite()
        print('保证金1=',保证金1)`

**Comment by we4t** [comment]
已检查，这一句写错了，应该是available：
if api.is_changing(account, "avaliable"): #可用资金有变化
