### ISSUE TITLE
osx系统 3.6 pip安装失败

### ISSUE THREAD

**Issue by th6666** [shinnytech/tqsdk-python#185]
ERROR: Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/3d/28/e74af1f93e5b4efdd79ddf4363f689bd0801a3037ba3741c9a5d85954a2c/tqsdk-1.1.0-py3-none-any.whl (Caused by NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x104b72b00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

**Comment by shinny-tianqin** [comment]
问题未重现
