### ISSUE TITLE
天勤客户端复盘和tqsdk联合使用时，sdk无法接收quote数据

### ISSUE THREAD

**Issue by realoptimusprime** [shinnytech/tqsdk-python#19]
天勤0.9.5;tqsdk 0.8.8

1. 运行python程序， 订阅日K， ticks，和quote
2. 天勤里指定某天复盘(比如2018-12-19)并启动

现象:
1. 天勤显示2018-12-18 15:14:59,并等待一段时间，这个时候python获得第一个日线(2018-12-18 00:00:00)
2. 天勤回放时间进行到21:00:30左右，python获得第二个日线(2018-12-19 00:00:00)

quote数据始终无法获得，除非重启python程序

**Comment by shinny-chengzhi** [comment]
建议贴出有问题的程序，我这里没法重现你说的问题

**Comment by realoptimusprime** [comment]
直接运行demo里的dualthrust.py即可复现(symbol改成rb1905)
注意操作顺序L
1. 天勤客户端里点历史复盘
2. 天勤客户端里选2018-12-19
3. 命令行启动dualthrust.py
4. 天勤客户端里点历史行情进入

并且，3和4之间的时间间隔长短不同也会导致命令行产生不同现象，比如crash，但是不变的是quote数据拿不到

**Comment by shinny-chengzhi** [comment]
需要先点 历史行情进入 并弹出控制对话框后才应启动策略
