### ISSUE TITLE
天勤终端的策略同品种实盘与回测 互相干扰？

### ISSUE THREAD

**Issue by victorzsl** [shinnytech/tqsdk-python#196]
在天勤中运行simnow实盘, IF策略一直开启，未关闭。
前一交易日有持仓，position.pos=-1
次日，早盘前对策略进行了昨日数据的回测，检查开平仓是否一致。
检查结果近似一致，相差不大。也保留了持仓，position.pos=-1。

随后删除回测。

早开盘，策略继续运行，
发现持仓居然为2手空仓了。（策略每分钟打印持仓）
position.pos=-2

大约9：45的样子，策略满足平仓条件，
开始平仓，报告仅平仓1手，另1手失败。

失败是正常的，因为simnow仅一手持仓。

不正常的是回测似乎干扰了实盘的position.pos值。
这是否一个Bug？

数据没有保留，请自行实验验证。

**Comment by we4t** [comment]
1. 回测和实盘运行是两套不同系统，不会影响到实盘
2. 可以检查下是否是其他问题，方便提供一下simnow账号吗，后台帮你查一下持仓信息

**Comment by victorzsl** [comment]
为了复现此问题，
11月19日上午，通过天勤开启策略，策略状态一直是正在运行。
早上在指定时间10:13:30下了一手Ni多单，
10:15~10:30休盘期间，对策略进行回测，
回测结束后，保留显示数据，
删除回测策略。

鼠标重新点开正在运行的策略，发现print不能窗口输出了。
显示信息停在10:15前不更新，
但策略似乎仍在运行，在指定时间10:31:30平仓了。

保留显示数据也没有10:15之后信息。

复现问题失败，但又冒出别的问题了。（删除回测后，正在运行的策略无法显示print信息）

**Comment by victorzsl** [comment]
simnow账号不方便提供，
我觉得跟simnow应该没啥关系，simnow持仓信息只有一手，这个是正确的。
而策略打印信息输出pos=-2 这个才是问题。
我再试图复现此问题。



在 2019-11-18 09:53:46，"shinny-limin" <notifications@github.com> 写道：

回测和实盘运行是两套不同系统，不会影响到实盘
可以检查下是否是其他问题，方便提供一下simnow账号吗，后台帮你查一下持仓信息

**Comment by we4t** [comment]
嗯感谢提出，我们这边测试了 发现是有问题，之后会尽快修好

**Comment by we4t** [comment]
即将发布的新版tqsdk为已修复版本，你可以关注发版后更新tqsdk，也可以提前在github上下载更新为当前最新的， commit ：50138a546e2146be4bfa01b2a52dcf1fb8de3330
