### ISSUE TITLE
api.is_changing(trade) 如何在trade字典里取到刚刚成交的那个？

### ISSUE THREAD

**Issue by victorzsl** [shinnytech/tqsdk-python#197]
tradelast定义为最近一个成交。
while True:
空格api.wait_update()
空格if api.is_changing(trade):
空格空格print("成交时间",tradelast.trade_date_time,"成交价格",tradelast.price)
但是如何找到这个刚刚成交的tradelast，需要遍历整个trade.values(),
找成交时间最近的那个，效率非常低，假如当天有几十几百个成交的话。有没有更为高效的办法？
由于返回字典, trade_id没有哪个函数返回？
或设计上能否考虑改为list或其它有序列表而不是字典？
这样上面的问题直接trade.values()[-1]取最后一个即可。

**Comment by we4t** [comment]
你可以保存一个历史所有trade id 的集合，然后每次判断is_changing(trade) 为True的时候，再次获取所有的trad id, 就是一个set(get_trade().keys())，然后用重新get到的所有trade id 集合减去原先那一份集合，就可以知道更新的trade id有哪些了。有可能一次数据更新会包含多条成交信息，并不是只有最后“一个”.

**Comment by victorzsl** [comment]
好方法，赞。

另外,因为你这样用set(get_trade().keys()) 而不是set(trade.keys())，
所以我搞不懂，

trade=get_trade()
在while True循环外设置一次,
然后直接tradeids=set(trade.keys())就好？

还是在循环里每次判断is_changing(trade) 都要
先trade=get_trade()
然后tradeids=set(trade.keys())  ?
