### ISSUE TITLE
quote.underlying_symbol在主力连续合约的历史回测中只有最新的合约

### ISSUE THREAD

**Issue by victorzsl** [shinnytech/tqsdk-python#198]
kq.m@SHFE.rb主力连续合约历史回测如果自2016年开始，
希望通过quote.underlying_symbol得到当时的主力合约，
但实际得到SHFE.rb2001合约, 没有得到预期的SHFE.rb1605.

也就是quote.underlying_symbol这种方法能实盘，但不能回测。

**Comment by we4t** [comment]
现在不能得到过去时间的主连的标的合约，这个之后我们会优化
