### ISSUE TITLE
天勤客户端复盘和tqsdk联合使用时,暂停行情回访控制，有时会导致sdk crash

### ISSUE THREAD

**Issue by realoptimusprime** [shinnytech/tqsdk-python#20]
1.启动天勤复盘
2.当天勤客户端弹出行情回访控制对话框后，运行python程序
3.中途暂停行情回访

python程序crash

**Comment by shinny-chengzhi** [comment]
能给出 crash 的 callstack 吗？这个用例我还没遇到 crash 过

**Comment by realoptimusprime** [comment]
下次出现了我贴上来，复现取决于执行的步骤和实际步骤之间的时间间隔，另外我的天勤客户端和python脚本在不同的机器上（api实例化的时候指定了url)
参见https://github.com/shinnytech/tqsdk-python/issues/19#issuecomment-452975998

**Comment by shinny-chengzhi** [comment]
参见 https://github.com/shinnytech/tqsdk-python/issues/19#issuecomment-453345098
