### ISSUE TITLE
quote and tick not at same time？

### ISSUE THREAD

**Issue by victorzsl** [shinnytech/tqsdk-python#201]
![tick and quote not at same time](https://user-images.githubusercontent.com/18364962/69153156-a8f57280-0b18-11ea-835f-5c29b199ca30.JPG)

如例图所示，一个空策略，不下单，仅打印tick计数编号，quote计数编号，wait_update计数编号。
if api.is_changing(quote) :打印xxx
if api.is_changing(tickSerial.iloc[-1]):打印xxx

可以看到第64对tick和quote之间相差了50毫秒，间隔了2次wait_update.
而第63对tick和quote之间相差了6毫秒，在同一个wait_update循环内处理完成.

1. tick和quote不是每0.5秒同时收到的一个信息么?为什么会相差50毫秒？
2. 如果间隔一个或2个wait_update, 大部分都是Quote先到，但也有Tick先到的，如下图。
我对上述现象不太理解。好像很随机的发生。

后续是否有可能在这些方面进行优化？保证一致性？

![tick before quote arrival](https://user-images.githubusercontent.com/18364962/69154891-c972fc00-0b1b-11ea-9c13-2ea6ff33ed7a.JPG)

**Comment by shinny-yangyang** [comment]
目前的行情服务器缺少事务化能力，quote/tick/kline 是由不同的服务分别提供的，互相之间没有刻意同步过，只要任意一个数据更新了就会触发发包动作．这个问题的解决需要等行情服务器修正，上线时间暂时还不确定
