### ISSUE TITLE
登录成功、成功下单、订单成交信息增加

### ISSUE THREAD

**Issue by Qweringo** [shinnytech/tqsdk-python#202]
2019-11-22 09:46:37,653 - INFO - 通知: 登录成功
像登录成功、成功下单、订单成交，都没有包含用户信息

当遇到用户一个主进程用多个线程装不同账户的tqapi的时候，控制台输出信息是没有办法区分哪个账户出来的信息的

是否需要在通知信息中加入用户信息如账户期货公司名和期货ID

**Comment by we4t** [comment]
客户端不做修改，转由服务器下发，我在open-trade-gateway提issue了
