### ISSUE TITLE
策略运行过程中能否绘图？

### ISSUE THREAD

**Issue by victorzsl** [shinnytech/tqsdk-python#205]
1. VS code的K线图主图下方有成交量图和持仓图，
在天勤终端中只有主K线图，没有成交量图和持仓图，
可否考虑增加？或者作为选项option由用户决定是否增加？

2. 策略运行过程中能否绘图？
比如可能用户在运行过程中绘MA图，压力支撑图，等等。
目前的方法,api.close()阻碍了这一点。
新的数据到来后无法继续绘图。

3. tick图中能否由用户选择是否增加Ask线图和Bid线图？
或也允许绘图？
目前的lastprice线图无法进一步分析价格是在Ask成交的还是在Bid成交的。
而drawline和drawtext目前只允许在k线图中绘制。

**Comment by we4t** [comment]
在策略运行过程中，可以把画图语句放在while True中，并且在while True中也要调用wait_update()函数以更新行情数据，这时画的指标线等图形就可以随着行情的变化而变化了。
这个示例我们之后会修改为如下使用while True的用法:
from tqsdk import TqApi
from tqsdk.ta import MA

api = TqApi()
klines = api.get_kline_serial("SHFE.au2006", 5)

ma = MA(klines, 30)  # 使用tqsdk自带指标函数计算均线
klines["ma_MAIN"] = ma.ma
# 在主图中画一根默认颜色（红色）的ma指标线

while True:
    api.wait_update()
    if api.is_changing(klines):
        ma = MA(klines, 30)  # 使用tqsdk自带指标函数计算均线
        klines["ma_MAIN"] = ma.ma

**Comment by we4t** [comment]
暂时不支持在tick上绘图
