### ISSUE TITLE
targetpos改为单例模式

### ISSUE THREAD

**Issue by shinny-chengzhi** [shinnytech/tqsdk-python#207]
按合约代码维护已创建的实例，如果已创建则直接返回之前的实例，暂不用考虑多线程的情况

**Comment by shinny-tianqin** [comment]
目前, 由于 TqSdk 未对创建TargetPosTask进行任何限制, 导致用户可能以一种错误的方式使用它, 即对一个合约创建多个TargetPosTask实例. 常见的错误场景是这样:

'''
while True:
    api.wait_update()
    tp = TargetPosTask(api, "SHFE.cu1901")
    tp.set_target_volume(1)
'''

这种情况下, 由于多个TargetPosTask实例间信息不同步, 可能导致多个实例分别执行下单, 使最终持仓手数超过预设值, 然后再由于超仓导致减仓动作, 使用户程序陷入 加仓-加仓过量-减仓-减仓过量的死循环, 迅速消耗大量手续费.
