### ISSUE TITLE
天勤复盘开始时刻主连和指数数据缺失

### ISSUE THREAD

**Issue by realoptimusprime** [shinnytech/tqsdk-python#21]
启动复盘功能(比如2018-12-19)，行情回访控制对话框上的时间从2018-12-18 15:14:59直接跳到2018-12-19 21:00:09, 开盘前几秒的quote数据没有

**Comment by shinny-chengzhi** [comment]
缺的是主连和指数的数据，具体合约的数据是没有缺失的

**Comment by realoptimusprime** [comment]
不只是主连和指数，即使指定了具体合约标的也有问题，参见https://github.com/shinnytech/tqsdk-python/issues/19#issuecomment-452975998

**Comment by shinny-chengzhi** [comment]
参见 https://github.com/shinnytech/tqsdk-python/issues/19#issuecomment-453345098
