### ISSUE TITLE
交易手续费计算错误

### ISSUE THREAD

**Issue by realoptimusprime** [shinnytech/tqsdk-python#25]
比如开3手rb1905的空单，sdk手续费算出来是2.40

"时间:2019-01-08 10:45:31.000000,合约:SHFE.rb1905,开平:OPEN,方向:SELL,手数:3,价格:3493.000,手续费:2.40"

**Comment by shinny-chengzhi** [comment]
模拟交易的手续费和保证金都是估计值，因为不同账户的费率是不一样的，除非让用户自己填，否则肯定是不准的

**Comment by dbsxdbsx** [comment]
@shinny-chengzhi ，那么问题就是，如何回测时自定义手续费呢？  毕竟实盘，每个人的手续费不仅和交易品种有关，和开户的期货公司也有关呀
