### ISSUE TITLE
增加获取多平、双平等信息的demo

### ISSUE THREAD

**Issue by shinny-limin** [shinnytech/tqsdk-python#254]

**Comment by gamcing** [comment]
我写了一个，仅供参考。
[https://github.com/gamcing/tqsdk-python/blob/master/tqsdk/tafunc_tick_msg.py](url)

**Comment by gamcing** [comment]
我写了一个，供参考：
[https://github.com/gamcing/tqsdk-python/blob/master/tqsdk/tafunc_tick_msg.py](https://github.com/gamcing/tqsdk-python/blob/master/tqsdk/tafunc_tick_msg.py)
