### ISSUE TITLE
回测订阅tick后，在交易时间段刚开始下单，可能无法成交

### ISSUE THREAD

**Issue by shinny-limin** [shinnytech/tqsdk-python#259]
订阅了tick时，如果指定回测开始时间为一个交易时间段的开始时间 而tick未更新数据，则导致无法成交（在sim增加交易时间判断之后）：当tick未更新时，quote时间停在上一个交易时间段，而回测时间在下一交易时间段开始，此时应成交 却报错”不在交易时间段内“.

（如果订阅的是K线，或未订阅，此问题也能触发；但当quote生成频率修改为在K线生成时也同时生成，此问题则不存在。）

**Comment by we4t** [comment]
修改方案：修改backtest.py 
在_ensure_quote()中，判断如果订阅了tick则同时订阅一个15分钟K线
同时，在_send_diff() 中填入quote_diff处判断，如果订阅的是tick则将15分钟线生成的quote的datetime下发（只用它来更新quote的时间）。即保证了在下一交易时间段开始时quote时间推动到这个时候

**Comment by we4t** [comment]
重现demo：
api = TqApi(backtest=TqBacktest(datetime(2019,10,2,10,30,59),datetime(2019,12,4))) # 无法下单
order = api.insert_order(symbol="DCE.m2005", direction="BUY", offset="OPEN", volume=5, limit_price=2750)
print(api.get_quote("DCE.m2005")["datetime"])
# tick=api.get_tick_serial("DCE.m2005")
while True:
    api.wait_update()

**Comment by shinny-limin** [comment]
新的修改方案：将可交易时间段改为用当前行情时间（它从回测的起始时间开始）来计算即可
