### ISSUE TITLE
行情服务器不支持从阿里云访问？

### ISSUE THREAD

**Issue by maxsonic** [shinnytech/tqsdk-python#26]
我尝试在阿里服务器上访问数据，一直是ssl handshake error。在我本地上是没有这个问题的。
而我测试requests访问其他https网站，也是没有这个问题。所以是不是行情服务器openmd.shinnytech.com屏蔽了阿里云？

**Comment by shinny-chengzhi** [comment]
目前行情服务器正在运维，可以使用天勤终端复盘功能 http://doc.shinnytech.com/pysdk/latest/faq.html#faq-debug

**Comment by maxsonic** [comment]
感谢。你回答完之后，我本机也访问不了了。
