### ISSUE TITLE
quote修改生成频率之后检查是否可以去除backtest下发的"_tqsdk_backtest"或其中的"current_dt"

### ISSUE THREAD

**Issue by we4t** [shinnytech/tqsdk-python#262]
目前在sim.py中只有在收到quote更新时才将self._current_datetime更新为quote["datetime"]或self._tqsdk_backtest["current_dt"]。在backtest.py中，只要下发了行情（无论此时是否生成quote),就一定会下发_tqsdk_backtest["current_dt"]数据，因此，在sim.py中更新self._current_datetime时quote的["datetime"]就和_tqsdk_backtest["current_dt"]是一样的，即无需判断是否是在回测过程中，都可以直接使用  self._current_datetime = max(quote["datetime"], self._current_datetime)  来更新（现测试了只用这一句话来更新self._current_datetime时，web_gui是可以生成正确时间账户资金图的）。

此时quote的更新频率比_tqsdk_backtest["current_dt"] 慢，因此也没有将所有情况都测试过。在修改quote的更新频率之后，可以重新检查测试，考虑是否将_tqsdk_backtest["current_dt"]去掉而直接使用quote["datetiem"]

**Comment by ElizabethMa** [comment]
commit 876084fc22205c94983496ab3223e6a2fd474a78 修改了相关问题。
目前修改为在sim.py中，
+ 在 backtest 模式由 _tqsdk_backtest['current_dt'] 更新 self._current_datetime
+ 其他模式下，由 max(quote["datetime"], self._current_datetime) 更新 self._current_datetime

backtest 模式下 quote 如果是不活跃合约，更新频率比 _tqsdk_backtest["current_dt"] 低，使用_tqsdk_backtest["current_dt"] 更新当前时间，更准确一些。
