### ISSUE TITLE
商品期权回测模式无法交易问题

### ISSUE THREAD

**Issue by gamcing** [shinnytech/tqsdk-python#288]
商品期权无法在回测模式中进行买卖交易：

log:
`
INFO - 模拟交易下单 87256b1c3ab4c05415b3cba121fc5b07: 时间:2020-02-04 14:32:59.999999,合约:DCE.i2005-C-560,开平:OPEN,方向:BUY,手数:1,价格:47.1
INFO - 模拟交易委托单 87256b1c3ab4c05415b3cba121fc5b07: 合约不存在
INFO - 模拟交易下单 3e6f3449727721972942aaa92469c0aa: 时间:2020-02-04 14:32:59.999999,合约:DCE.i2005-P-560,开平:OPEN,方向:SELL,手数:1,价格:19.5
INFO - 模拟交易委托单 3e6f3449727721972942aaa92469c0aa: 合约不存在
INFO - 模拟交易下单 14679d41f0d1d13d8804d581c8f8ac40: 时间:2020-02-04 14:32:59.999999,合约:DCE.i2005-C-540,开平:OPEN,方向:BUY,手数:1,价格:61.0
INFO - 模拟交易委托单 14679d41f0d1d13d8804d581c8f8ac40: 合约不存在
INFO - 模拟交易下单 fba8b0ac84e4db86d0ae8656fe42f9b0: 时间:2020-02-04 14:32:59.999999,合约:DCE.i2005-P-540,开平:OPEN,方向:SELL,手数:1,价格:14.6
INFO - 模拟交易委托单 fba8b0ac84e4db86d0ae8656fe42f9b0: 合约不存在
INFO - 模拟交易下单 c675040a5ddea771b078ff9d0ece8798: 时间:2020-02-04 14:32:59.999999,合约:DCE.i2005-C-750,开平:OPEN,方向:BUY,手数:1,价格:2.2
INFO - 模拟交易委托单 c675040a5ddea771b078ff9d0ece8798: 合约不存在
INFO - 模拟交易下单 c281ef137f972cae57572b5a789f952f: 时间:2020-02-04 14:32:59.999999,合约:DCE.i2005-P-750,开平:OPEN,方向:SELL,手数:1,价格:164.20000000000002
INFO - 模拟交易委托单 c281ef137f972cae57572b5a789f952f: 合约不存在
INFO - 模拟交易下单 a728a81f31d5db1e98b130de5b3c48b6: 时间:2020-02-04 14:35:59.999999,合约:DCE.i2005-C-720,开平:OPEN,方向:BUY,手数:1,价格:3.1
INFO - 模拟交易委托单 a728a81f31d5db1e98b130de5b3c48b6: 合约不存在
INFO - 模拟交易下单 7db94b4325d2856c48a6e4081a4c0d5f: 时间:2020-02-04 14:35:59.999999,合约:DCE.i2005-P-720,开平:OPEN,方向:SELL,手数:1,价格:134.0
INFO - 模拟交易委托单 7db94b4325d2856c48a6e4081a4c0d5f: 合约不存在
INFO - 模拟交易下单 3cd1bd72f4c669b92660208d700c97a1: 时间:2020-02-04 14:35:59.999999,合约:DCE.i2005-C-740,开平:OPEN,方向:BUY,手数:1,价格:2.5
INFO - 模拟交易委托单 3cd1bd72f4c669b92660208d700c97a1: 合约不存在
INFO - 模拟交易下单 bad17bc9e2feaca7776b878b32fc459c: 时间:2020-02-04 14:35:59.999999,合约:DCE.i2005-P-740,开平:OPEN,方向:SELL,手数:1,价格:153.20000000000002
INFO - 模拟交易委托单 bad17bc9e2feaca7776b878b32fc459c: 合约不存在
INFO - 模拟交易下单 e6de3a7a6790a2d1e3fbb8b84b8aa19b: 时间:2020-02-04 14:35:59.999999,合约:DCE.i2005-C-520,开平:OPEN,方向:BUY,手数:1,价格:78.19999999999999
INFO - 模拟交易委托单 e6de3a7a6790a2d1e3fbb8b84b8aa19b: 合约不存在
INFO - 模拟交易下单 8916b9ca4d23532a87bcac3181a90160: 时间:2020-02-04 14:35:59.999999,合约:DCE.i2005-P-520,开平:OPEN,方向:SELL,手数:1,价格:10.3
INFO - 模拟交易委托单 8916b9ca4d23532a87bcac3181a90160: 合约不存在
INFO - 模拟交易下单 4501512bb166573aea84b9b834afd01e: 时间:2020-02-04 14:40:59.999999,合约:DCE.i2005-C-530,开平:OPEN,方向:BUY,手数:1,价格:70.89999999999999
INFO - 模拟交易委托单 4501512bb166573aea84b9b834afd01e: 合约不存在`

**Comment by shinny-xuyida** [comment]
商品期权回测这块tqsdk目前还不支持，会尽快支持

**Comment by shinny-mayanqiong** [comment]
version 1.7.0(2020/04/16) 已支持
