### ISSUE TITLE
task was destroyed but it is pending问题如何解决

### ISSUE THREAD

**Issue by DerekCyrus** [shinnytech/tqsdk-python#29]
程序运行一段时间后就出现如上报错，求问大神如何解决

**Comment by DerekCyrus** [comment]
该下载程序用于下载期货tick数据，出现上述问题前总会遇到不存在的期货数据下载，但是本应判定其文件大小为0然后继续下载，不知为何一直卡在这里

**Comment by shinny-chengzhi** [comment]
通常遇到 task was destroyed but it is pending 不会引发业务逻辑错误
遇到不存在的合约，可以加入超时判断。
