### ISSUE TITLE
没有获取交易所 所有品种的 各个合约代码的 函数

### ISSUE THREAD

**Issue by liuminglm** [shinnytech/tqsdk-python#30]
获取数据要使用代码，比如“SHFE.rb1905”，我看了一下代码，好像没有找到获取交易所所有品种的各个合约代码的函数

**Comment by shinny-chengzhi** [comment]
目前没有提供公开的接口获取所有合约，如果确实需要的话可以手动遍历 api.data["quotes"]

**Comment by allenwoods** [comment]
> 获取数据要使用代码，比如“SHFE.rb1905”，我看了一下代码，好像没有找到获取交易所所有品种的各个合约代码的函数

可以用[akshare](https://www.akshare.xyz/zh_CN/latest/data/futures/futures.html)来获取主力合约代码, 数据来源新浪
```python
import akshare as ak
dce_contract = ak.match_main_contract(exchange="dce") #大商所
czce_contract = ak.match_main_contract(exchange="czce") # 郑商所
shfe_contract = ak.match_main_contract(exchange="shfe") # 上期所
cffex_contract = ak.match_main_contract(exchange="cffex") # 中金所
```
