### ISSUE TITLE
ta.py 使用了talib作为基础函数库 但是talib的sma和国内的不大一致

### ISSUE THREAD

**Issue by yutiansut** [shinnytech/tqsdk-python#34]
受影响的指标例如 KDJ
https://github.com/shinnytech/tqsdk-python/blob/master/tqsdk/ta.py

国内一般使用的sma 是威廉sma 
参考实现代码
https://github.com/QUANTAXIS/QUANTAXIS/blob/master/QUANTAXIS/QAIndicator/base.py#L50
以及 joinquant的一个讨论贴:
 参考https://www.joinquant.com/post/867

这样算出来的 和国内的软件算出来的基本比对一致

**Comment by shinny-chengzhi** [comment]
最新版使用的 ta.py 已经没有这个问题了
