### ISSUE TITLE
对天勤数据的期待

### ISSUE THREAD

**Issue by victorzsl** [shinnytech/tqsdk-python#38]
如果天勤能提供所有合约自上市开始的Tick数据，堪称业内典范。
或能提供自自上市开始的1分钟K线数据，也非常棒。
目前仅有2016年之后的数据。遗憾满满。

非常期待信易的做为,  使天勤成为量化领域的最受欢迎的软件。
![tianqin](https://user-images.githubusercontent.com/18364962/55086715-d2721180-50e3-11e9-9b36-18083ae066b7.jpg)

**Comment by shinny-tianqin** [comment]
对于目前市场上可交易的合约, 我们可以覆盖从上市到最新的全部数据.
对于已经下市的合约, 数据最多只能到 2016年
