### ISSUE TITLE
关于参数优化

### ISSUE THREAD

**Issue by victorzsl** [shinnytech/tqsdk-python#39]
目前国内的量化交易和研发软件，绝大多数都没有配备可用的优化算法做参数优化。
期待天勤能突破国内的瓶颈，支持采用优化算法做参数优化。
包括但不限于诸如GA遗传算法，PSO，等等优化算法。

（为什么国外最流行的软件MT5/MC等都支持优化算法？而国内很少支持？只能呵呵了）

**Comment by shinny-chengzhi** [comment]
目前没有框架层面的支持，如果你现在想自己做的话可以 expect BacktestFinished 例外，记录回测结果，然后重新构建 api 回测下一组参数
