### ISSUE TITLE
请问 2.x 版本的代码不再开源了吗？

### ISSUE THREAD

**Issue by lucywang000** [shinnytech/tqsdk-python#392]
在尝试解决 #391 时，发现 TqAuth 这个类在  github 上 clone  下来的代码中根本找不到，才发现 pypi 中最新版本是 2.2.0, 但是这个仓库里最近一个版本是五个月前的 1.8。

<img width="385" alt="Screen Shot 2020-12-09 at 5 50 51 PM" src="https://user-images.githubusercontent.com/30067222/101613752-18514380-3a47-11eb-90c9-0280031905eb.png">

当然直接 pip install 也能看到源代码，但是这样一来是比较麻烦，二来是想要贡献代码的话就麻烦一些了。

**Comment by shinny-xuyida** [comment]
首先感谢想要给我们贡献源码
现在tqsdk的代码已经从github开源改动到pip之后本地开源
原因是因为，tqsdk会使用到一些和pc端会共用的算法模块等价值较高信息，因此会先进行cython编译后再提供给用户使用，所以不再方便在github进行全部开源的方式

**Comment by lucywang000** [comment]
哦，理解。建议在 README 里把这一条加进去吧。
