### ISSUE TITLE
螺纹的主力合约是哪个代码？

### ISSUE THREAD

**Issue by viponedream** [shinnytech/tqsdk-python#4]
螺纹的主力合约是哪个代码？

**Comment by shinny-chengzhi** [comment]
主力合约的代码是 KQ.m@ 开头的
螺纹主力就是 KQ.m@SHFE.rb

**Comment by snake3342** [comment]
那就是下单和订阅行情quote的时候，主力合约都会被对应到具体的合约是吧？那么如果是开仓的时候以rb1901开的多一手，这个仓位一直在，然后主力合约变成rb1905了，现在要先平仓后反向，此时targetpos这个功能的后端会不会知道当前的持仓是+1手，然后平1901，开1905？

**Comment by shinny-chengzhi** [comment]
目前主力合约是不能拿来交易的，交易相关数据都是直接指定交易所合约代码的。

**Comment by snake3342** [comment]
图表数据和订阅行情，都可以用主力合约的是吧？

**Comment by shinny-chengzhi** [comment]
是的，行情相关数据可以使用主力合约

**Comment by snake3342** [comment]
KQ.m 的主力合约跟具体合约的对应关系，从哪个地方取？

**Comment by shinny-chengzhi** [comment]
最新版的 api 可以通过 underlying_symbol 字段获得主力合约跟具体合约的对应关系
