### ISSUE TITLE
api.insert_order(symbol="ZCE.cf1905", direction="BUY", offset="OPEN", volume=1, limit_price=1)有返回值？

### ISSUE THREAD

**Issue by basicsp** [shinnytech/tqsdk-python#41]
上述指令有3个问题：
1. symbol不合法，应该是ZCE.cf905，写成ZCE.cf1905没有报错
2. limit_price=1，超过了跌停价
3. 实际上应该是非法指令，但可以下单，并可以用get_order查询
返回信息如下：如何判断下单成功？
{'_listener': set(),
 '_path': ['trade', '（隐去）', 'orders', '745a6d77f0da4f8d8fca00bdf7f65f46'],
 'direction': 'BUY',
 'exchange_id': 'ZCE',
 'exchange_order_id': '',
 'insert_date_time': 0,
 'instrument_id': 'cf1905',
 'last_msg': '',
 'limit_price': nan,
 'offset': 'OPEN',
 'order_id': '745a6d77f0da4f8d8fca00bdf7f65f46',
 'price_type': '',
 'status': 'ALIVE',
 'time_condition': '',
 'volume_condition': '',
 'volume_left': 1,
 'volume_orign': 1}

**Comment by basicsp** [comment]
抱歉，上述cf905应为大写“CF905”

**Comment by shinny-chengzhi** [comment]
合约代码填错或超出张跌停板会在之后收到服务器返回的错单通知，并且委托单的 status 字段为 FINISHED
