### ISSUE TITLE
最小开仓数量为0，无法知道交易所品种的最小下单数量，导致下单失败

### ISSUE THREAD

**Issue by loversgzl** [shinnytech/tqsdk-python#474]
通过：api.get_quote(symbol) 获取的信息中，只有最大开仓数量：max_limit_order_volume，最小开仓数量：min_limit_order_volume 都是0，导致部分品种不满足最小下单数量。

**Comment by shinny-mayanqiong** [comment]
请使用 最小市价开仓手数 `open_min_market_order_volume` 或者 最小限价开仓手数 `open_min_limit_order_volume`
