### ISSUE TITLE
如何取消合约数据的自动更新？

### ISSUE THREAD

**Issue by 4ever911** [shinnytech/tqsdk-python#48]
比如说， 

q = api.get_quote("SHFE.cu1812")  
klines = api.get_kline_serial("SHFE.cu1812", 10)  

while api.wait_update() 等待后，q和klines就会自动更新，但是如果我监控的数据比较多，比如我只是临时用了几个合约 5/30/dayily kline数据， 因为没有函数取消这些合约的自动更新， 是否会造成数据太多，影响网络速度？

**Comment by 4ever911** [comment]
假设自动化策略是一个基于tick数据的，我根本不需要考虑kline，但是程序有UI， 每次切换不同合约时，会展示当前kline数据，切换别的合约后就不需要之前的数据，（目前好像无法取消更新？）， 这样如果把所有合约看一下，不同周期看以下，会额外增加很多不需要的数据更新，担心会影响网络，继而影响自动策略的运行。

**Comment by 4ever911** [comment]
不小心点到close了。。。

**Comment by shinny-chengzhi** [comment]
目前没有提供接口退订数据，如果担心数据太多影响网速的话可以在 get_kline_serial 及 get_tick_serial 时指定相同的 chart_id, 这样前面发的请求都会被退订
