### ISSUE TITLE
类似get_trades的函数没有提供吗？

### ISSUE THREAD

**Issue by 4ever911** [shinnytech/tqsdk-python#50]
如何获取成交记录呢？需要client自己来维护吗？

**Comment by shinny-tianqin** [comment]
我们还未确定是否要提供一个单独的 get_trades 函数. 目前你可以用
api.data["trade"][user_id]["trades"] 来获取全部成交记录, 这些记录同样是在 wait_update 时更新

**Comment by shinny-tianqin** [comment]
从 0.9.6 版本开始, order增加了一个属性 order.trade_records, 可以获取委托单对应的成交记录. order.trade_price 可以获取委托单的平均成交价
