### ISSUE TITLE
如何取得某個品種的保證金杠桿比例？

### ISSUE THREAD

**Issue by 4ever911** [shinnytech/tqsdk-python#51]
只看到合約乘數，沒有找到保證金杠桿比例值，這個可以取到嗎？

**Comment by shinny-tianqin** [comment]
目前无法取得

**Comment by 4ever911** [comment]
能否增加这个功能，在仓位管理的时候，很需要这个值。 我看是可以从CTP取到 ShortMarginRatioByMoney 等一些值。

**Comment by shinny-tianqin** [comment]
暂时没有增加的计划, 建议您对自己需要交易的合约, 在程序中人工维护一个保证金率参数
