### ISSUE TITLE
pos_long_today 和 volume_long_today 有什么区别？

### ISSUE THREAD

**Issue by 4ever911** [shinnytech/tqsdk-python#75]
看描述都是 多头今仓手数

**Comment by 4ever911** [comment]
position 和 volume的区别?  position是1个单位头寸？ 希望文档有更详细的描述。

**Comment by we4t** [comment]
1. 在定义上：pos_long_today是根据交易所的计算规则计算的手数，volume_long_today是根据ctp的计算规则计算的手数；
2. 现在实际使用中：实盘是直接把从ctp获取到的volume_long_today显示出来（没有再经过其他的计算修改），模拟不连ctp，因此是将pos_long_today和volume_long_today都按照交易所的计算规则来计算的（即他们数值相同）
