### ISSUE TITLE
请检查客户端及网络是否正常

### ISSUE THREAD

**Issue by Lion2017** [shinnytech/tqsdk-python#77]
经常出现 “请检查客户端及网络是否正常” 怎么解决啊？

**Comment by Lion2017** [comment]
![image](https://user-images.githubusercontent.com/25025488/60897313-71d5a180-a29a-11e9-8fbe-5838d9edafa1.png)

**Comment by we4t** [comment]
可能是客户端网络问题，需要具体分析
