### ISSUE TITLE
单独分离合约服务, 加快 tqsdk 启动速度

### ISSUE THREAD

**Issue by shinny-tianqin** [shinnytech/tqsdk-python#83]

**Comment by 4ever911** [comment]
支持！ 我每次登陆对所有quote做了一个迭代，主要就是迭代所有KQ.m@  取主力合约对应的真实underline_symbol, 后面都是根据bar来处理，但是仍然浪费不少资源在几十个主力合约quote的自动更新上（这些数据我根本用不到）， 

或者对quote要是能制定一个代码是否订阅就好。（服务器肯定订阅所有行情对更新，但是不要发送diff给我通知我，我只需要bar的更新）

**Comment by we4t** [comment]
等待 新合约服务 实时合约信息上线后修改。新合约服务不再将所有合约信息下发，而是客户端向服务器发出请求。

**Comment by shinny-mayanqiong** [comment]
解决方案：对接新版合约服务 - Duplicate of #234
