### ISSUE TITLE
天勤终端工作正常，但是程序化接口TqApi不工作

### ISSUE THREAD

**Issue by AixuanDai** [shinnytech/tqsdk-python#9]
运行api = TqApi("SIM")报错：
![image](https://user-images.githubusercontent.com/29666161/49718483-2e2fa080-fc95-11e8-888d-fd3fefc8f31f.png)

**Comment by shinny-chengzhi** [comment]
参见  faq: https://github.com/shinnytech/tqsdk-python/blob/master/doc/faq.rst#%E8%BF%90%E8%A1%8C%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81%E5%90%8E%E6%8F%90%E7%A4%BA-runtimeerror-cannot-run-the-event-loop-while-another-loop-is-running
