### ISSUE TITLE
Mac ssl 问题

### ISSUE THREAD

**Issue by kingdjf** [shinnytech/tqsdk-python#93]
使用mac mojave的时候，在pycharm中会ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)与 wss://openmd.shinnytech.com/t/md/front/mobile 的网络连接断开，请检查客户端及网络是否正常！！这个问题，请问一下，这个问题应该如何解决，谢谢。
![image](https://user-images.githubusercontent.com/20849778/61386332-ae327e80-a8e6-11e9-946f-ab85e2949888.png)

**Comment by zshchou** [comment]
一样的情况，怎么解？

**Comment by kingdjf** [comment]
哈哈，放弃了------------------ 原始邮件 ------------------
发件人: "zsh chou"<notifications@github.com>
发送时间: 2019年8月14日(星期三) 凌晨1:17
收件人: "shinnytech/tqsdk-python"<tqsdk-python@noreply.github.com>;
抄送: "段剑锋"<kingdjf@foxmail.com>;"Author"<author@noreply.github.com>;
主题: Re: [shinnytech/tqsdk-python] Mac ssl 问题 (#93)



一样的情况，怎么解？
 
&mdash;

**Comment by ElizabethMa** [comment]
在 Finder 中打开 `Applications` -> `Python 3.x` ,  双击 `Install Certificates.command`。
参考 [https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify](mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify)
