### ISSUE TITLE
get_order api改进

### ISSUE THREAD

**Issue by zLulus** [shinnytech/tqsdk-python#94]
接口：   
https://doc.shinnytech.com/tqsdk/latest/reference/tqsdk.api.html?highlight=order#tqsdk.api.TqApi.get_order   
希望可以添加“是否只查询Alive的order”，或者查询时间范围，来解决查出很多Finish的order的问题，以提高查询效率   
谢谢！

**Comment by we4t** [comment]
（" 不填order_id参数调用本函数, 将返回包含用户所有委托单的一个dict, 其中每个元素的key为委托单号, value为 Order" ）
可以修改策略代码实现：
不填单号，然后遍历这个dict，判断并取出其中status（委托单状态）为ALIVE的委托单；或判断其insert_date_time（下单时间）是否在你所选定的时间范围内
