### ISSUE TITLE
get_tick_serial 怎么获取指定时间区间的数据 并且返回的datatime字段时间显示有问题

### ISSUE THREAD

**Issue by qianxuanyon** [shinnytech/tqsdk-python#96]
不清楚那个序列id参数是什么格式 如何填写

例如我想获取2017-07-19这一天所有的tick数据 应该怎么做 或者获取某个合约全部Tick数据的方法

返回时间需要+8小时才是正常国内时间
图中获取的是CZCE.AP910合约
![image](https://user-images.githubusercontent.com/29041881/61588383-1b872d80-abcd-11e9-9b11-ff16c2009047.png)

**Comment by we4t** [comment]
下载历史行情使用download工具，demo: 
https://github.com/shinnytech/tqsdk-python/blob/master/tqsdk/demo/tutorial/downloader.py
