### ISSUE TITLE
SHFE不支持市价单

### ISSUE THREAD

**Issue by 4ever911** [shinnytech/tqsdk-python#97]
通知: 下单失败,已撤单报单被拒绝SHFE:不被支持的报单类型

客户端程序可以自己用涨/跌停价格来报单，但是能不能在sdk里面支持，这样client不用作特殊处理，保持接口一致性？

**Comment by we4t** [comment]
SHFE不支持市价，因此下单（ insert_order() ）时需填写limit_price字段。可以在代码中获取买一/卖一价然后填入insert_order的limit_price字段，
